version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      timezone: "UTC"
    labels:
      - "dependencies"
      - "automerge"
    groups:
      production-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "@types/*"
          - "eslint*"
          - "prettier*"
          - "typescript"
      development-dependencies:
        dependency-type: "development"
        patterns:
          - "@types/*"
          - "eslint*"
          - "prettier*"
          - "typescript"
    open-pull-requests-limit: 10
    versioning-strategy: auto
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "deps"
      prefix-development: "dev-deps"
      include: "scope"
    reviewers:
      - "owner"
    pull-request-branch-name:
      separator: "-"
