version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
      # Check on Mondays
      day: "monday"
      # Use UTC timezone
      timezone: "UTC"
    # Specify labels for pull requests
    labels:
      - "dependencies"
      - "automerge"
    # Group dependencies together
    groups:
      # Group production dependencies
      production-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "@types/*"
          - "eslint*"
          - "prettier*"
          - "typescript"
      # Group development dependencies
      development-dependencies:
        dependency-type: "development"
        patterns:
          - "@types/*"
          - "eslint*"
          - "prettier*"
          - "typescript"
    # Limit the number of open pull requests
    open-pull-requests-limit: 10
    # Configure version update behavior
    versioning-strategy: auto
    # Allow up-to-date dependencies to be maintained
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
    # Customize commit messages
    commit-message:
      prefix: "deps"
      prefix-development: "dev-deps"
      include: "scope"
    # Add reviewers
    reviewers:
      - "owner"
    # Configure pull request settings
    pull-request-branch-name:
      separator: "-"
    # Security updates configuration
    security-updates:
      enabled: true 